import { Inter } from 'next/font/google'
import './globals.css'
//import Logo from './components/logo'
import NavLink from './components/navBar'
import Footer from './components/footer'
//import { NavLink } from 'react-router-dom'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <NavLink/>
        {children}
        <Footer/>
        </body>
     
      
      
    </html>
  )
}
